CREATE DATABASE expert_soft;
USE expert_soft;

CREATE TABLE customers (
id_customer INT AUTO_INCREMENT PRIMARY KEY,
customer_user VARCHAR (255) NOT NULL,
address VARCHAR (255) NOT NULL,
phone VARCHAR (255) NOT NULL,
email VARCHAR (255) UNIQUE NOT NULL
);